"""empty message

Revision ID: 10dbf522121e
Revises: 
Create Date: 2025-03-25 19:38:09.033669

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10dbf522121e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('INVESGSS_EMPRESAS',
    sa.Column('C_EMPRESA_ID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('D_NOMBRE', sa.String(length=50), nullable=False),
    sa.Column('C_CIF', sa.String(length=10), nullable=True),
    sa.Column('D_EMAIL', sa.String(length=50), nullable=False),
    sa.Column('C_USR_CREACION', sa.String(length=10), nullable=True),
    sa.Column('F_CREACION', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('C_USR_MODIFICACION', sa.String(length=10), nullable=True),
    sa.Column('F_MODIFICACION', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('C_EMPRESA_ID')
    )
    op.create_table('INVEGSS_SISTEMAS',
    sa.Column('C_SISINFO_ID', sa.String(length=10), nullable=False),
    sa.Column('D_NOMBRE', sa.String(length=50), nullable=False),
    sa.Column('C_RESPONSABLE_TECNICO_ID', sa.Integer(), nullable=True),
    sa.Column('C_RESPONSABLE_FUNCIONAL_ID', sa.Integer(), nullable=True),
    sa.Column('F_PUESTA_PRODUCCION', sa.Date(), nullable=True),
    sa.Column('F_SALIDA_PRODUCCION', sa.Date(), nullable=True),
    sa.Column('D_OBSERVACIONES', sa.Text(), nullable=True),
    sa.Column('C_USR_CREACION', sa.String(length=10), nullable=True),
    sa.Column('F_CREACION', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('C_USR_MODIFICACION', sa.String(length=10), nullable=True),
    sa.Column('F_MODIFICACION', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['C_RESPONSABLE_FUNCIONAL_ID'], ['INVESGSS_EMPRESAS.C_EMPRESA_ID'], ),
    sa.ForeignKeyConstraint(['C_RESPONSABLE_TECNICO_ID'], ['INVESGSS_EMPRESAS.C_EMPRESA_ID'], ),
    sa.PrimaryKeyConstraint('C_SISINFO_ID')
    )
    op.create_table('INVESGSS_COMPONENTES',
    sa.Column('C_SISINFO_ID', sa.String(length=10), nullable=False),
    sa.Column('C_COMPONENTE_ID', sa.String(length=10), nullable=False),
    sa.Column('C_COMPONENTE_PADRE_ID', sa.String(length=10), nullable=True),
    sa.Column('D_NOMBRE', sa.String(length=50), nullable=False),
    sa.Column('D_GIT_PROJECT', sa.String(length=500), nullable=True),
    sa.Column('D_OBSERVACIONES', sa.Text(), nullable=True),
    sa.Column('C_USR_CREACION', sa.String(length=10), nullable=True),
    sa.Column('F_CREACION', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('C_USR_MODIFICACION', sa.String(length=10), nullable=True),
    sa.Column('F_MODIFICACION', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['C_SISINFO_ID', 'C_COMPONENTE_PADRE_ID'], ['INVESGSS_COMPONENTES.C_SISINFO_ID', 'INVESGSS_COMPONENTES.C_COMPONENTE_ID'], ),
    sa.ForeignKeyConstraint(['C_SISINFO_ID'], ['INVEGSS_SISTEMAS.C_SISINFO_ID'], ),
    sa.PrimaryKeyConstraint('C_SISINFO_ID', 'C_COMPONENTE_ID')
    )
    op.create_table('INVESGSS_EMPRESAS_COMPONENTES',
    sa.Column('C_EMPRESA_ID', sa.Integer(), nullable=False),
    sa.Column('C_SISINFO_ID', sa.String(length=10), nullable=False),
    sa.Column('C_COMPONENTE_ID', sa.String(length=10), nullable=False),
    sa.Column('F_INICIO', sa.Date(), nullable=False),
    sa.Column('F_FIN', sa.Date(), nullable=True),
    sa.Column('C_ROL_ID', sa.Enum('JEFE_DE_PROYECTO', 'ANALISTA', 'DESARROLLADOR', name='rolasignacionenum'), nullable=False),
    sa.ForeignKeyConstraint(['C_EMPRESA_ID'], ['INVESGSS_EMPRESAS.C_EMPRESA_ID'], ),
    sa.ForeignKeyConstraint(['C_SISINFO_ID', 'C_COMPONENTE_ID'], ['INVESGSS_COMPONENTES.C_SISINFO_ID', 'INVESGSS_COMPONENTES.C_COMPONENTE_ID'], ),
    sa.PrimaryKeyConstraint('C_EMPRESA_ID', 'C_SISINFO_ID', 'C_COMPONENTE_ID', 'F_INICIO')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('INVESGSS_EMPRESAS_COMPONENTES')
    op.drop_table('INVESGSS_COMPONENTES')
    op.drop_table('INVEGSS_SISTEMAS')
    op.drop_table('INVESGSS_EMPRESAS')
    # ### end Alembic commands ###
