"""empty message

Revision ID: 22c6536df2a5
Revises: 378f358b2781
Create Date: 2025-03-27 18:40:50.988664

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '22c6536df2a5'
down_revision = '378f358b2781'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('INVESGSS_UNIDADES_DIR3', schema=None) as batch_op:
        batch_op.alter_column('N_NIVE_JERARQUICO',
                              existing_type=sa.INTEGER(),
                              nullable=True)
        batch_op.drop_column('N_NIVEL_JERARQUICO')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('INVESGSS_UNIDADES_DIR3', schema=None) as batch_op:
        batch_op.add_column(sa.Column('N_NIVEL_JERARQUICO', sa.INTEGER(), nullable=True))
        batch_op.alter_column('N_NIVE_JERARQUICO',
                              existing_type=sa.INTEGER(),
                              nullable=False)

    # ### end Alembic commands ###
