"""empty message

Revision ID: 378f358b2781
Revises: 10dbf522121e
Create Date: 2025-03-27 18:36:53.577942

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '378f358b2781'
down_revision = '10dbf522121e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('INVESGSS_UNIDADES_DIR3',
                    sa.Column('C_ID_UD_ORGANICA', sa.String(length=9), nullable=False),
                    sa.Column('C_DNM_UD_ORGANICA', sa.String(length=150), nullable=False),
                    sa.Column('N_NIVE_JERARQUICO', sa.Integer(), nullable=False),
                    sa.Column('C_ID_DEP_UD_SUPERIOR', sa.String(length=9), nullable=True),
                    sa.Column('NIF_CIF', sa.String(length=9), nullable=True),
                    sa.Column('C_DNM_UD_ORGANICA.1', sa.String(length=150), nullable=True),
                    sa.ForeignKeyConstraint(['C_ID_DEP_UD_SUPERIOR'], ['INVESGSS_UNIDADES_DIR3.C_ID_UD_ORGANICA'], ),
                    sa.PrimaryKeyConstraint('C_ID_UD_ORGANICA')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('INVESGSS_UNIDADES_DIR3')
    # ### end Alembic commands ###
