"""empty message

Revision ID: 709b5dc8d307
Revises: 
Create Date: 2025-03-19 23:08:10.865438

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '709b5dc8d307'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('AUTHZ_APLICACIONES',
    sa.Column('C_APLICACION_ID', sa.String(length=10), nullable=False),
    sa.Column('D_NOMBRE', sa.String(length=50), nullable=False),
    sa.Column('C_USR_CREACION', sa.String(length=10), nullable=True),
    sa.Column('F_CREACION', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('C_USR_MODIFICACION', sa.String(length=10), nullable=True),
    sa.Column('F_MODIFICACION', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('C_APLICACION_ID')
    )
    op.create_table('AUTHZ_TIPOS_AMBITOS',
    sa.Column('C_TP_AMBITO_ID', sa.String(length=10), nullable=False),
    sa.Column('D_TP_AMBITO', sa.String(length=50), nullable=False),
    sa.Column('D_RESTRICCION', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('C_TP_AMBITO_ID')
    )
    op.create_table('AUTHZ_PERMISOS',
    sa.Column('C_APLICACION_ID', sa.String(length=10), nullable=False),
    sa.Column('C_PERMISO_ID', sa.String(length=50), nullable=False),
    sa.Column('D_NOMBRE', sa.String(length=50), nullable=False),
    sa.Column('C_USR_CREACION', sa.String(length=10), nullable=True),
    sa.Column('F_CREACION', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('C_USR_MODIFICACION', sa.String(length=10), nullable=True),
    sa.Column('F_MODIFICACION', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['C_APLICACION_ID'], ['AUTHZ_APLICACIONES.C_APLICACION_ID'], ),
    sa.PrimaryKeyConstraint('C_APLICACION_ID', 'C_PERMISO_ID')
    )
    op.create_table('AUTHZ_ROLES',
    sa.Column('C_APLICACION_ID', sa.String(length=10), nullable=False),
    sa.Column('C_ROL_ID', sa.String(length=10), nullable=False),
    sa.Column('D_NOMBRE', sa.String(length=50), nullable=False),
    sa.Column('C_USR_CREACION', sa.String(length=10), nullable=True),
    sa.Column('F_CREACION', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('C_USR_MODIFICACION', sa.String(length=10), nullable=True),
    sa.Column('F_MODIFICACION', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['C_APLICACION_ID'], ['AUTHZ_APLICACIONES.C_APLICACION_ID'], ),
    sa.PrimaryKeyConstraint('C_APLICACION_ID', 'C_ROL_ID')
    )
    op.create_table('AUTHZ_ASGN_PERMISOS',
    sa.Column('C_PRINCIPAL_ID', sa.String(length=100), nullable=False),
    sa.Column('C_APLICACION_ID', sa.String(length=10), nullable=False),
    sa.Column('C_PERMISO_ID', sa.String(length=50), nullable=False),
    sa.Column('N_ORDEN', sa.Numeric(precision=3), nullable=False),
    sa.Column('C_TP_AMBITO_ID', sa.String(length=10), nullable=True),
    sa.Column('D_AMBITO', sa.String(length=40), nullable=True),
    sa.ForeignKeyConstraint(['C_APLICACION_ID', 'C_PERMISO_ID'], ['AUTHZ_PERMISOS.C_APLICACION_ID', 'AUTHZ_PERMISOS.C_PERMISO_ID'], ),
    sa.ForeignKeyConstraint(['C_TP_AMBITO_ID'], ['AUTHZ_TIPOS_AMBITOS.C_TP_AMBITO_ID'], ),
    sa.PrimaryKeyConstraint('C_PRINCIPAL_ID', 'C_APLICACION_ID', 'C_PERMISO_ID', 'N_ORDEN')
    )
    op.create_table('AUTHZ_ASGN_ROLES',
    sa.Column('C_PRINCIPAL_ID', sa.String(length=100), nullable=False),
    sa.Column('C_APLICACION_ID', sa.String(length=10), nullable=False),
    sa.Column('C_ROL_ID', sa.String(length=10), nullable=False),
    sa.Column('N_ORDEN', sa.Numeric(precision=3), nullable=False),
    sa.Column('C_TP_AMBITO_ID', sa.String(length=10), nullable=True),
    sa.Column('D_AMBITO', sa.String(length=40), nullable=True),
    sa.Column('F_INICIO', sa.DateTime(timezone=True), nullable=True),
    sa.Column('F_FIN', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['C_APLICACION_ID', 'C_ROL_ID'], ['AUTHZ_ROLES.C_APLICACION_ID', 'AUTHZ_ROLES.C_ROL_ID'], ),
    sa.ForeignKeyConstraint(['C_TP_AMBITO_ID'], ['AUTHZ_TIPOS_AMBITOS.C_TP_AMBITO_ID'], ),
    sa.PrimaryKeyConstraint('C_PRINCIPAL_ID', 'C_APLICACION_ID', 'C_ROL_ID', 'N_ORDEN')
    )
    op.create_table('AUTHZ_ROLES_PERMISOS',
    sa.Column('C_APLICACION_ID', sa.String(length=10), nullable=False),
    sa.Column('C_ROL_ID', sa.String(length=10), nullable=False),
    sa.Column('C_PERMISO_ID', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['C_APLICACION_ID', 'C_PERMISO_ID'], ['AUTHZ_PERMISOS.C_APLICACION_ID', 'AUTHZ_PERMISOS.C_PERMISO_ID'], ),
    sa.ForeignKeyConstraint(['C_APLICACION_ID', 'C_ROL_ID'], ['AUTHZ_ROLES.C_APLICACION_ID', 'AUTHZ_ROLES.C_ROL_ID'], ),
    sa.PrimaryKeyConstraint('C_APLICACION_ID', 'C_ROL_ID', 'C_PERMISO_ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('AUTHZ_ROLES_PERMISOS')
    op.drop_table('AUTHZ_ASGN_ROLES')
    op.drop_table('AUTHZ_ASGN_PERMISOS')
    op.drop_table('AUTHZ_ROLES')
    op.drop_table('AUTHZ_PERMISOS')
    op.drop_table('AUTHZ_TIPOS_AMBITOS')
    op.drop_table('AUTHZ_APLICACIONES')
    # ### end Alembic commands ###
