"""empty message

Revision ID: a1760e125f43
Revises: a98b01abc894
Create Date: 2025-03-27 18:45:24.378166

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a1760e125f43'
down_revision = 'a98b01abc894'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('INVESGSS_UNIDADES_DIR3', schema=None) as batch_op:
        batch_op.add_column(sa.Column('N_NIVEL_JERARQUICO', sa.Integer(), nullable=True))
        batch_op.drop_column('N_NIVE_JERARQUICO')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('INVESGSS_UNIDADES_DIR3', schema=None) as batch_op:
        batch_op.add_column(sa.Column('N_NIVE_JERARQUICO', sa.INTEGER(), nullable=True))
        batch_op.drop_column('N_NIVEL_JERARQUICO')

    # ### end Alembic commands ###
