"""empty message

Revision ID: a98b01abc894
Revises: 22c6536df2a5
Create Date: 2025-03-27 18:42:47.723156

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a98b01abc894'
down_revision = '22c6536df2a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('INVESGSS_UNIDADES_DIR3', schema=None) as batch_op:
        batch_op.add_column(sa.Column('C_DNM_UD_ORGANICA_SUPERIOR', sa.String(length=150), nullable=True))
        batch_op.drop_column('C_DNM_UD_ORGANICA.1')
        batch_op.drop_column('N_NIVEL_JERARQUICO')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('INVESGSS_UNIDADES_DIR3', schema=None) as batch_op:
        batch_op.add_column(sa.Column('N_NIVEL_JERARQUICO', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('C_DNM_UD_ORGANICA.1', sa.VARCHAR(length=150), nullable=True))
        batch_op.drop_column('C_DNM_UD_ORGANICA_SUPERIOR')

    # ### end Alembic commands ###
