INSERT INTO INVE_SISTEMAS (C_SISINFO_ID, D_NOMBRE, C_RESPONSABLE_TECNICO_ID, C_UNIDAD_FUNCIONAL_ID, F_PUESTA_PRODUCCION, F_SALIDA_PRODUCCION, D_OBSERVACIONES, C_USR_CREACION, F_CREACION, C_USR_MODIFICACION, F_MODIFICACION) VALUES ('AUTHZ', 'Sistema de Autorización', null, 'A07033436', null, null, '<p>Muy <strong>BONITO </strong>a ratos</p>
<p><span style="text-decoration: underline;">Solo me quedo contigo</span></p>', null, '2025-04-14 18:02:20', null, null);

INSERT INTO INVE_TIPOS_COMPONENTE(C_TP_COMPONENTE_ID, D_NOMBRE)
VALUES ('SPRINGBOOT', 'Spring Boot');
INSERT INTO INVE_TIPOS_COMPONENTE(C_TP_COMPONENTE_ID, D_NOMBRE)
VALUES ('ANGULAR', 'Angular');

INSERT INTO INVE_COMPONENTES (C_SISINFO_ID, C_COMPONENTE_ID, C_TP_COMPONENTE_ID, C_COMPONENTE_PADRE_ID, D_NOMBRE, D_GIT_PROJECT, D_OBSERVACIONES, C_USR_CREACION, F_CREACION, C_USR_MODIFICACION, F_MODIFICACION) VALUES ('AUTHZ', 'FRONTEND', 'ANGULAR', null, 'Frontend de gestión', 'https://servicios.jcyl.es/gitlab/gerencia-de-servicios-sociales/shss/authz/authz-frontend.git', '<h1>FEO</h1>', null, '2025-04-15 11:45:22', null, null);
INSERT INTO INVE_COMPONENTES (C_SISINFO_ID, C_COMPONENTE_ID, C_TP_COMPONENTE_ID, C_COMPONENTE_PADRE_ID, D_NOMBRE, D_GIT_PROJECT, D_OBSERVACIONES, C_USR_CREACION, F_CREACION, C_USR_MODIFICACION, F_MODIFICACION) VALUES ('AUTHZ', 'BACKEND', 'SPRINGBOOT', null, 'Backend de servicios', 'https://servicios.jcyl.es/gitlab/gerencia-de-servicios-sociales/shss/authz/authz-backend.git', '<h1>BONITO</h1>', null, '2025-04-15 11:47:09', null, null);
