"""empty message

Revision ID: aa3cb5f82a70
Revises: 
Create Date: 2025-04-14 19:37:04.578809

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'aa3cb5f82a70'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('INVE_PERSONAS',
                    sa.Column('C_PERSONA_ID', sa.Integer(), autoincrement=True, nullable=False),
                    sa.Column('D_NOMBRE', sa.String(length=50), nullable=False),
                    sa.Column('D_APELLIDO1', sa.String(length=50), nullable=False),
                    sa.Column('D_APELLIDO2', sa.String(length=50), nullable=False),
                    sa.Column('D_EMAIL', sa.String(length=50), nullable=False),
                    sa.Column('D_LDAP_ID', sa.String(length=50), nullable=True),
                    sa.Column('C_USR_CREACION', sa.String(length=10), nullable=True),
                    sa.Column('F_CREACION', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'),
                              nullable=False),
                    sa.Column('C_USR_MODIFICACION', sa.String(length=10), nullable=True),
                    sa.Column('F_MODIFICACION', sa.DateTime(timezone=True), nullable=True),
                    sa.PrimaryKeyConstraint('C_PERSONA_ID')
                    )
    op.create_table('INVE_UNIDADES_DIR3',
                    sa.Column('C_ID_UD_ORGANICA', sa.String(length=9), nullable=False),
                    sa.Column('C_DNM_UD_ORGANICA', sa.String(length=150), nullable=False),
                    sa.Column('N_NIVEL_JERARQUICO', sa.Integer(), nullable=True),
                    sa.Column('C_ID_DEP_UD_SUPERIOR', sa.String(length=9), nullable=True),
                    sa.Column('NIF_CIF', sa.String(length=9), nullable=True),
                    sa.Column('C_DNM_UD_ORGANICA_SUPERIOR', sa.String(length=150), nullable=True),
                    sa.ForeignKeyConstraint(['C_ID_DEP_UD_SUPERIOR'], ['INVE_UNIDADES_DIR3.C_ID_UD_ORGANICA'], ),
                    sa.PrimaryKeyConstraint('C_ID_UD_ORGANICA')
                    )
    op.create_table('INVE_SISTEMAS',
                    sa.Column('C_SISINFO_ID', sa.String(length=10), nullable=False),
                    sa.Column('D_NOMBRE', sa.String(length=50), nullable=False),
                    sa.Column('C_RESPONSABLE_TECNICO_ID', sa.Integer(), nullable=True),
                    sa.Column('C_UNIDAD_FUNCIONAL_ID', sa.String(length=9), nullable=True),
                    sa.Column('F_PUESTA_PRODUCCION', sa.Date(), nullable=True),
                    sa.Column('F_SALIDA_PRODUCCION', sa.Date(), nullable=True),
                    sa.Column('D_OBSERVACIONES', sa.Text(), nullable=True),
                    sa.Column('C_USR_CREACION', sa.String(length=10), nullable=True),
                    sa.Column('F_CREACION', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'),
                              nullable=False),
                    sa.Column('C_USR_MODIFICACION', sa.String(length=10), nullable=True),
                    sa.Column('F_MODIFICACION', sa.DateTime(timezone=True), nullable=True),
                    sa.ForeignKeyConstraint(['C_RESPONSABLE_TECNICO_ID'], ['INVE_PERSONAS.C_PERSONA_ID'], ),
                    sa.ForeignKeyConstraint(['C_UNIDAD_FUNCIONAL_ID'], ['INVE_UNIDADES_DIR3.C_ID_UD_ORGANICA'], ),
                    sa.PrimaryKeyConstraint('C_SISINFO_ID')
                    )
    op.create_table('INVE_COMPONENTES',
                    sa.Column('C_SISINFO_ID', sa.String(length=10), nullable=False),
                    sa.Column('C_COMPONENTE_ID', sa.String(length=10), nullable=False),
                    sa.Column('C_TP_COMPONENTE_ID', sa.String(length=20), nullable=False),
                    sa.Column('C_COMPONENTE_PADRE_ID', sa.String(length=10), nullable=True),
                    sa.Column('D_NOMBRE', sa.String(length=50), nullable=False),
                    sa.Column('D_GIT_PROJECT', sa.String(length=500), nullable=True),
                    sa.Column('D_OBSERVACIONES', sa.Text(), nullable=True),
                    sa.Column('C_USR_CREACION', sa.String(length=10), nullable=True),
                    sa.Column('F_CREACION', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'),
                              nullable=False),
                    sa.Column('C_USR_MODIFICACION', sa.String(length=10), nullable=True),
                    sa.Column('F_MODIFICACION', sa.DateTime(timezone=True), nullable=True),
                    sa.ForeignKeyConstraint(['C_SISINFO_ID', 'C_COMPONENTE_PADRE_ID'],
                                            ['INVE_COMPONENTES.C_SISINFO_ID', 'INVE_COMPONENTES.C_COMPONENTE_ID'], ),
                    sa.ForeignKeyConstraint(['C_SISINFO_ID'], ['INVE_SISTEMAS.C_SISINFO_ID'], ),
                    sa.PrimaryKeyConstraint('C_SISINFO_ID', 'C_COMPONENTE_ID')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('INVE_COMPONENTES')
    op.drop_table('INVE_SISTEMAS')
    op.drop_table('INVE_UNIDADES_DIR3')
    op.drop_table('INVE_PERSONAS')
    # ### end Alembic commands ###
