"""empty message

Revision ID: cf5ef28ee92f
Revises: 
Create Date: 2025-04-13 12:37:44.513880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf5ef28ee92f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('INVE_SISTEMAS',
    sa.Column('C_SISTEMA_ID', sa.String(length=30), nullable=False),
    sa.Column('D_NOMBRE', sa.String(length=50), nullable=False),
    sa.Column('C_UNIDAD_FUNCIONAL_ID', sa.String(length=9), nullable=True),
    sa.Column('D_OBSERVACIONES', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('C_SISTEMA_ID')
    )
    op.create_table('INVE_COMPONENTES',
    sa.Column('C_SISTEMA_ID', sa.String(length=30), nullable=False),
    sa.Column('C_COMPONENTE_ID', sa.String(length=30), nullable=False),
    sa.Column('D_NOMBRE', sa.String(length=50), nullable=False),
    sa.Column('D_URL_PROYECTO_GIT', sa.String(length=255), nullable=True),
    sa.Column('D_OBSERVACIONES', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['C_SISTEMA_ID'], ['INVE_SISTEMAS.C_SISTEMA_ID'], ),
    sa.PrimaryKeyConstraint('C_SISTEMA_ID', 'C_COMPONENTE_ID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('INVE_COMPONENTES')
    op.drop_table('INVE_SISTEMAS')
    # ### end Alembic commands ###
