version: '3.7'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=authz
      - POSTGRES_USER=authz
      - POSTGRES_DB=authz

  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - ./redisdata:/data
    #environment:
      #REDIS_ARGS: "--requirepass pe11gr0s0"
